// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpzdruhkfxovfnigpdom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wemRydWhrZnhvdmZuaWdwZG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTUwNjUsImV4cCI6MjA2NDU5MTA2NX0.MCdSgJRlgiAVdeVegfiO2m9H9ImakvyoQXeEd4FNsxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);